#!/usr/bin/env bash
# A script that checks my configuration for my domain

check_domain()
{
    if [ $# -eq 2 ]; then
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk \
	'{split($1, spl, ".")} {printf "The subdomain %s is a %s record and points to %s\n",spl[1],$4,$5}'
    elif [ $# -eq 1 ]; then
	for subdomain in 'www' 'lb-01' 'web-01' 'web-02'; do
	    f_domain=$subdomain.$1
	    dig "$f_domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk \
	'{split($1, spl, ".")} {printf "The subdomain %s is a %s record and points to %s\n",spl[1],$4,$5}'
	done
    fi
}

check_domain "$1" "$2"
