#!/usr/bin/env bash
# A script that transfers a file from our client to a server automatically

if (( $# < 4 ))
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
