#!/usr/bin/env bash
# A script that installs a nginx web server on a server
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
