#!/usr/bin/env bash
# A script that automatically configures a new server
cp /etc/nginx/nginx.conf /home/nginx

apt-get -y update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi
