#!/usr/bin/env bash
# a script that prints the contents of the file "/etc/passwd"
# It is customized to print only the username, user ID, and home directory path

while read -r passwd;
do
	echo "$passwd" | cut --delimiter=":" --fields=1,3,6
done < "/etc/passwd"
