#!/usr/bin/env bash
# This script displays numbers 1 to 20 then 
# bad luck numbers for china after 4, japan after 9, and italy after 17

i=1;

while ((i<21))
do
	echo "$i"

	case $i in
		"4") echo "bad luck from china";;
		"9") echo "bad luck from japan";;
		"17") echo "bad luck from italy";;
	esac
	((i++))
done
