#!/usr/bin/env bash
# A script that configures ubuntu server local host to 127.0.0.2 and facebook.com to 8.8.8.8
cat /etc/hosts > ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cat ~/hosts.new > /etc/hosts
