#!/bin/usr/env bash
# A bash script that generates an RSA key pair
# # Requirements:
#   - Name of the created private key must be school
#   - Number of bits in the created key should be 4096
#   - The key to use passpharse "betty"
ssh-keygen -b 4096 -f school -N betty
